### ISSUE TITLE
Weird behaviour with header and list items

### ISSUE THREAD

**Issue by upmygit** [rg-software/wlx-markdown-viewer#8]
Hi, I just downloaded your plugin, and noticed a weird behaviour with this [test.md](https://github.com/rg-software/wlx-markdown-viewer/files/13794744/test.md)
Because of the empty second item, everything gets the same font as the header, which is not wanted.
Maybe you are able to fix this.

Example here is different than in the result in the list viewer:

## Some header
- A list item
-

**Comment by rg-software** [comment]
Well, this behavior isn't in my code, it is a part of Hoedown. In any case, I am not sure what is the correct way of rendering this. Your markup has a line of text and a dash on the next line. Hoedown believes this is a second-level heading, just like in this case:

```
bla-bla
-------
```

**Comment by upmygit** [comment]
I haven't examined the sources, so I wasn't aware it is processed by an external library.

The plugin within Total Commander List view shows this:

**With an empty second item, the first item is shown as a second header**
![image](https://github.com/rg-software/wlx-markdown-viewer/assets/39409204/a69f69e3-f82f-4e65-99af-f523a81648ae)

**With a filled second item, it looks better**
![image](https://github.com/rg-software/wlx-markdown-viewer/assets/39409204/f3b522e3-3e30-4e50-b619-c7bd96019476)

It's not a big problem though. ;-)

**Comment by rg-software** [comment]
Yes. As I said, your "empty second item" is actually a dash. So what you have is the first item and a dash right beneath it. This is treated as a second-level heading (see [Alternate syntax](https://www.markdownguide.org/basic-syntax/)).

**Comment by JamoCA** [comment]
The markdown documentation doesn't contain the key phrase "second-level heading"... the example uses "Heading level 2".

When I initially saw this reported rendering bug, I compared the results against results rendered by Github/Gist, [VSCode](https://code.visualstudio.com/), [Markdown Monster](https://markdownmonster.west-wind.com/), [QOwnNotes](https://www.qownnotes.org/) and [CodeLib](https://fishcodelib.com/CodeLib.htm).  All of these programs render this as an empty list item instead of alternate "heading level 2".  (Except QOwnNotes. It suppresses the rendering of empty list items.)

The official description for "[Alternate Syntax](https://www.markdownguide.org/basic-syntax/#horizontal-rule-best-practices)" indicates that:

> Alternatively, on the line below the text, add any number of `==` characters for heading level 1 or `--` characters for heading level 2.

It explicitly states "any number of `--` characters"?  (It doesn't state "any number of `-` characters".)  I believe that alternate syntax requires at least 2 characters based on the example. The WLX plugin incorrectly interprets the single dash as "heading level 2".

If 2 dashes are on the last new line in a list without anything after it, the 2 dashes are visually appended to the prior list item when rendered in the Markdown editors/viewers that I referenced; except for the WLX plugin.

Please note that empty list items within the list are rendered incorrectly as headers (not just the last item).

```md
# Some header

- First list item
- Second list item
- 
- Last list item?
- 

Here is some text that follows...
```

This is displayed as:

![markdown-wlx-plugin-20240101092117](https://github.com/rg-software/wlx-markdown-viewer/assets/1112671/ee341013-0ed8-4e70-bbf1-700783ac72c4)

Consequently, [Hoedown](https://github.com/hoedown/hoedown) hasn't been updated in at least 9 years, but still manages to generate acceptable HTML for the most part.  As a Hoedown bug, it's not going to get fixed anytime soon and should probably be reported to their project where it won't get fixed, but at least be documented.

My recommendation would be to not use empty list elements.  (I personally don't use alternate syntax or have needed to include empty list elements.)

**Comment by rg-software** [comment]
> It explicitly states "any number of `--` characters"? (It doesn't state "any number of `-` characters".) I believe that alternate syntax requires at least 2 characters based on the example. The WLX plugin incorrectly interprets the single dash as "heading level 2".

[Release-20240102.zip](https://github.com/rg-software/wlx-markdown-viewer/files/13806333/Release-20240102.zip)

Look, if the fix is as simple as making sure there are at least two dashes / equality signs, I can add this check to the Hoedown code. Please test the attached revision.

**Comment by JamoCA** [comment]
I tried "Release-20240102.zip" and there didn't seem to be any difference.  (Empty list items are rendered as alternate syntax for a header.)

**Comment by rg-software** [comment]
> I tried "Release-20240102.zip" and there didn't seem to be any difference. (Empty list items are rendered as alternate syntax for a header.)

My bad, try this one please.
[Release-20240103.zip](https://github.com/rg-software/wlx-markdown-viewer/files/13815014/Release-20240103.zip)
It renders empty item as `-`, which is better I guess.

**Comment by JamoCA** [comment]
Yes!  It looks much better.

Since the orphaned dash doesn't match the alternate syntax pattern for a header, it falls back and is appended as a regular dash to the previous list item.  This behavior is now consistent with all the commercial markdown editors that I use. Thanks!

**Comment by upmygit** [comment]
Oh nice! Thanks for fixing the small issue.

@rg-software Will you include the fix in the repository as well?
@JamoCA Thank you for helping out!

**Comment by rg-software** [comment]
Sure. It's already there; also will be included into the next release (when there is one).
